### ISSUE TITLE
Gameplay TODO: feat/fe-gameboard

### ISSUE THREAD

**Issue by cesoun** [koneill6/cst-350-clc#10]
I need this to track progress since there are a few moving parts here and I want to make sure I hit all over them.

- [x] Board Partial
  - [x] Minesweeper Board
    - [x] Click Handlers
  - [x] Reset Button
  - [x] Score Label
- [x] Board AJAX
  - [x] Get
  - [x] Reveal (Left Click)
  - [x] Reset
- [x] Controllers
  - [x] Get
  - [x] Reveal (Left Click)
  - [x] Reset
- [x] Session Store (Singleton)
- [x] UserModel Update
  - [x] AccountService Update
  - [x] AccountDAO Update
- [x]  Update GameService
  - [x] Take Session Inputs
  - [x] Any Additional?
  
This looks fat but I have most the base stuff setup and should be able to crank it out in a couple hours.
